### ISSUE TITLE
initial feedbacks

### ISSUE THREAD

**Issue by bbelderbos** [IshanMi/responsible-twitterfeed#1]
@IshanMi as there is no PR let me comment here for now:

- Please include an .env.example file as per best practice to set environment variables

- I don't think Flask needs to know about the Twitter API keys, you could load them into the `feed_creator` module directly. Also  `get_api gets` gets called for every visit, it's probably better to do this once in the `feed_creator` module (you could turn the functions there into a class to persist state).

- It's more Pythonic to "ask for permission" (see https://devblogs.microsoft.com/python/idiomatic-python-eafp-versus-lbyl/), and this is a nice use case of the `min` builtin (in `get_search_term`):

```
try:
    quantity = min(int(quantity), 100)
except ValueError:
    quantity = 10
```

- I am missing templates and static folders.

- I would move `app.py` out of the project root folder into `src` possibly making it a separate `web` package there.

- Let me request API keys (Twitter added an approval process) unless I can borrow yours?

HTH
Bob

**Comment by IshanMi** [comment]
Hey Bob, this was really helpful advice- in particular the idea of turning the functions in feed_creator to a separate class. I wouldn't have thought of that!

I made all the above changes and sent you my .env file with the API keys as an example
